# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-03 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwtlc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='borrower_info',
        ),
        migrations.AddField(
            model_name='applicationsummary',
            name='asset_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.AssetSummary', verbose_name='Asset Summary'),
        ),
        migrations.AddField(
            model_name='assetsummary',
            name='managed_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.ManagedProperty', verbose_name='Managed Property Information'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.Address', verbose_name='Branch Address'),
        ),
    ]
