# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwtlc', '0002_auto_20180803_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgagedesired',
            name='if_not_listed',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Desired Term (if not listed)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='currentmortgage',
            name='current_term',
            field=models.CharField(help_text='Months remaining of total (e.g. 45 of 120)', max_length=255, verbose_name='Current Term'),
        ),
        migrations.AlterField(
            model_name='currentmortgage',
            name='date_loan_originated',
            field=models.CharField(max_length=30, verbose_name='Date Loan Originated'),
        ),
        migrations.AlterField(
            model_name='currentmortgage',
            name='late_payments',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='Have you made any late payments?'),
        ),
        migrations.AlterField(
            model_name='mortgagedesired',
            name='payment_desired',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Desired Payment of About'),
        ),
        migrations.AlterField(
            model_name='mortgagedesired',
            name='term_desired',
            field=models.IntegerField(choices=[(0, '20 Year'), (1, '15 Year'), (2, '10 Year'), (3, 'Less than 10 Years'), (4, 'Other')], default=0, verbose_name='Desired Term'),
        ),
        migrations.AlterField(
            model_name='mortgagedesired',
            name='time_frame',
            field=models.IntegerField(choices=[(0, 'Immediately'), (1, 'Within a Month'), (2, 'Within 6 Months')], default=0, verbose_name='Ready to Move Forward'),
        ),
        migrations.AlterField(
            model_name='propertyinforequest',
            name='lease_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Lease Rate'),
        ),
        migrations.AlterField(
            model_name='propertyinforequest',
            name='occupancy_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Occupancy Rate'),
        ),
        migrations.AlterField(
            model_name='propertyinforequest',
            name='property_address',
            field=models.ForeignKey(help_text="Select property from list, or click '+' to add new property.", on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.Address'),
        ),
        migrations.AlterField(
            model_name='propertyinforequest',
            name='rent',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Current Loan Payment'),
        ),
    ]
