# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-24 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwtlc', '0002_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanterms',
            name='approval_date',
            field=models.DateField(default='1999-08-08', help_text='mm/dd/yy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationsummary',
            name='tier',
            field=models.IntegerField(choices=[(0, 'Basic'), (1, 'Standard')], default=0),
        ),
        migrations.AlterField(
            model_name='currentmortgage',
            name='date_loan_originated',
            field=models.DateField(help_text='(mm/dd/yy)', verbose_name='Date Loan Originated'),
        ),
        migrations.AlterField(
            model_name='newrequestsummary',
            name='status',
            field=models.IntegerField(choices=[(0, 'Sleep'), (1, 'Active'), (2, 'Priority'), (3, 'Basic'), (4, 'Standard')], default=1),
        ),
    ]
