# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-24 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwtlc', '0003_auto_20180724_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsummary',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
