# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wwwtlc', '0005_auto_20180725_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyinforequest',
            name='property_use',
        ),
        migrations.AlterField(
            model_name='borrowerinforequest',
            name='fico',
            field=models.IntegerField(choices=[(0, '720+'), (1, '690-719'), (2, '660-679'), (3, '630-659'), (4, 'Unknown')], default=0, help_text='(approximate FICO)', verbose_name='FICO'),
        ),
        migrations.AlterField(
            model_name='loanterms',
            name='approval_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='mm/dd/yyyy'),
        ),
        migrations.AlterField(
            model_name='mortgagedesired',
            name='term_desired',
            field=models.IntegerField(choices=[(0, '20 Year'), (1, '15 Year'), (2, '10 Year'), (3, 'Less than 10 Years')], default=0, verbose_name='Desired Term'),
        ),
        migrations.AlterField(
            model_name='mortgagedesired',
            name='time_frame',
            field=models.IntegerField(choices=[(0, 'Immediately'), (1, 'Within a Month'), (2, 'Within 6 Months')], default=0, verbose_name='Desired Time Frame'),
        ),
        migrations.AlterField(
            model_name='propertyinforequest',
            name='property_type',
            field=models.IntegerField(choices=[(0, 'Commercial'), (1, 'Industrial'), (2, 'Residential'), (3, 'Mixed')], default=0, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=127, verbose_name='Blockchain Address'),
        ),
    ]
