# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwtlc', '0006_auto_20180726_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerinfo',
            name='mail_addr',
            field=models.ForeignKey(help_text='(required)', on_delete=django.db.models.deletion.CASCADE, related_name='mail_address', to='wwwtlc.Address', verbose_name='Mailing Address'),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='principal_office_addr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='principal_office_addres', to='wwwtlc.Address', verbose_name='Principal Office Address'),
        ),
    ]
