# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwtlc', '0007_auto_20180726_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.Address'),
        ),
    ]
