# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwtlc', '0009_auto_20180730_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerinfo',
            name='living_yrs',
            field=models.IntegerField(help_text='(required)', verbose_name='Years at Present Address'),
        ),
    ]
