# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-31 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwtlc', '0011_auto_20180730_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsummary',
            name='application',
        ),
        migrations.AlterField(
            model_name='applicationsummary',
            name='tier',
            field=models.IntegerField(choices=[(0, 'Basic'), (1, 'Standard'), (2, 'Converted')], default=0),
        ),
    ]
