# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-31 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwtlc', '0012_auto_20180731_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acknowledgeagree',
            name='borrower_agree',
        ),
        migrations.RemoveField(
            model_name='acknowledgeagree',
            name='coborrower_agree',
        ),
        migrations.AddField(
            model_name='acknowledgeagree',
            name='applicant_agree',
            field=models.BooleanField(default=False, verbose_name="Applicant's acknowledgement and agreement"),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='blockchain',
            field=models.IntegerField(choices=[(0, 'eth'), (1, 'ropsten'), (2, 'mainnet')], default=0),
        ),
    ]
