# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-01 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwtlc', '0013_auto_20180731_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrequestsummary',
            name='status',
            field=models.IntegerField(choices=[(0, 'Sleep'), (1, 'Active'), (2, 'Priority'), (3, 'Basic'), (4, 'Standard'), (5, 'Submitted')], default=1),
        ),
    ]
