# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wwwtlc', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_ID', models.CharField(max_length=254)),
                ('loan_address', models.CharField(max_length=254)),
                ('borrower_id', models.CharField(max_length=254)),
                ('contact_person_id', models.CharField(max_length=254)),
                ('loan_officer_id', models.CharField(max_length=254)),
                ('loan_data_id', models.CharField(max_length=254)),
                ('loan_payment_monthly', models.DecimalField(decimal_places=4, max_digits=100)),
                ('estimated_payments', models.IntegerField()),
                ('loan_request_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('loan_intrate_current', models.DecimalField(decimal_places=2, max_digits=100)),
                ('loan_intrate_start', models.DecimalField(decimal_places=2, max_digits=100)),
                ('loan_principle', models.DecimalField(decimal_places=2, max_digits=100)),
                ('loan_principle_paid', models.DecimalField(decimal_places=2, max_digits=100)),
                ('loan_interest_paid', models.DecimalField(decimal_places=2, max_digits=100)),
                ('loan_currency', models.CharField(default='USD', max_length=3)),
                ('loan_partner', models.CharField(max_length=254)),
                ('loan_approve_date', models.DateField()),
                ('addressID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.Address')),
                ('contracts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.Contract')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Loan')),
            ],
        ),
    ]
