# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-03 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wwwtlc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_payment_due', models.DecimalField(decimal_places=4, help_text='Approved monthly payment', max_digits=12)),
                ('loan_payment_due_date', models.DateField(default=django.utils.timezone.now)),
                ('payments_left', models.IntegerField(help_text='Months until loan is paid')),
                ('loan_balance', models.DecimalField(decimal_places=18, help_text='Remaining balance left on loan', max_digits=65)),
                ('loan_intrate_current', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Current interest rate')),
                ('loan_intrate_start', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Starting interest rate')),
                ('loan_principal', models.DecimalField(decimal_places=4, max_digits=15)),
                ('loan_principal_paid', models.DecimalField(decimal_places=4, max_digits=15)),
                ('loan_interest_paid', models.DecimalField(decimal_places=4, max_digits=15)),
                ('loan_approve_date', models.DateField(default=django.utils.timezone.now)),
                ('TLC_balance', models.DecimalField(decimal_places=18, help_text='TLC owned by TLC from loan payment', max_digits=65)),
                ('borrower_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='wwwtlc.Borrower', verbose_name='Borrower ID')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_status', models.IntegerField(choices=[(0, 'active'), (1, 'suspended'), (2, 'foreclosure'), (3, 'closed')], default=0)),
                ('borrower_type', models.IntegerField(choices=[(0, 'Individual'), (1, 'Married Couple'), (2, 'Partnership'), (3, 'Corporation'), (4, 'Limited Liability Company'), (5, 'Trust'), (6, 'Investment Group'), (7, 'Other')], default=0)),
                ('loan_type', models.IntegerField(choices=[(0, 'FIXED'), (1, 'ARM')], default=0)),
                ('loan_currency', models.CharField(default='USD', max_length=3)),
                ('contact_person', models.ForeignKey(help_text='The facilitator for loan processing', on_delete=django.db.models.deletion.CASCADE, related_name='contact_person', to='wwwtlc.Person')),
                ('contracts', models.ForeignKey(blank=True, help_text='(optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.Contract')),
                ('loan_address', models.ForeignKey(help_text='The address of the property needing financed', on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.Address')),
                ('loan_partner', models.ForeignKey(blank=True, default=1, help_text='(optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_partner', to='wwwtlc.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_requested', models.CharField(help_text='At time of loan request, the person/entity trying to borrow the money', max_length=60, verbose_name='Borrower')),
                ('loan_request_amt', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Desired loan amount')),
                ('loan_payment_request', models.DecimalField(decimal_places=4, help_text='Desired monthly payment', max_digits=12)),
                ('loan_intrate_request', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Desired interest rate')),
                ('loan_request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('workflow_status', models.IntegerField(choices=[(0, 'Sleep'), (1, 'Active'), (2, 'Tier 1'), (3, 'Tier 2'), (4, 'Priority')], default=1)),
                ('request_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Loan_Data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.IntegerField(choices=[(0, 'Incomplete'), (1, 'Processing'), (2, 'Completed'), (3, 'N/A')], default=0)),
                ('approval_status', models.IntegerField(choices=[(0, 'Denied'), (1, 'Approved')], default=0)),
                ('loan_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan.Loan_Data')),
                ('loan_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_officer', to='wwwtlc.Person')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_data', to='loan.Loan_Data'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.Wallet'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
