# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_remove_loan_data_addressid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_data',
            name='contracts',
        ),
    ]
