# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_remove_loan_data_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_data',
            name='loan_status',
            field=models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('foreclosure', 'foreclosure'), ('closed', 'closed')], default='active', max_length=12),
        ),
        migrations.AddField(
            model_name='loan_data',
            name='loan_type',
            field=models.CharField(choices=[('TYPE_FIXED', 'TYPE_FIXED'), ('TYPE_ARM', 'TYPE_ARM')], default='TYPE_FIXED', max_length=12),
        ),
    ]
