# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20180504_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_data',
            name='data_id',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
