# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwtlc', '__first__'),
        ('loan', '0005_loan_data_data_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='estimated_payments',
            new_name='loan_payment_quantity',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='contact_person_id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_ID',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_data_id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_officer_id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_payment_monthly',
        ),
        migrations.RemoveField(
            model_name='loan_data',
            name='data_id',
        ),
        migrations.RemoveField(
            model_name='loan_data',
            name='loan',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_data',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='loan_data', to='loan.Loan_Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_officer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='loan_officer', to='wwwtlc.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_payment_request',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_payment_required',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan_data',
            name='TLC_balance',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan_data',
            name='borrower_requested',
            field=models.CharField(default='none', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan_data',
            name='contact_person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contact_person', to='wwwtlc.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan_data',
            name='contracts',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.Contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan_data',
            name='loan_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='wwwtlc.Borrower'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_address', to='wwwtlc.Address'),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_balance',
            field=models.DecimalField(decimal_places=18, max_digits=80),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_interest_paid',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_intrate_current',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_intrate_start',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_partner', to='wwwtlc.Partner'),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_principle',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_principle_paid',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_status',
            field=models.IntegerField(choices=[(0, 'active'), (1, 'suspended'), (2, 'foreclosure'), (3, 'closed')], default=0),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_type',
            field=models.IntegerField(choices=[(0, 'TYPE_FIXED'), (1, 'TYPE_ARM'), (2, 'TYPE_SHARIAH')], default=0),
        ),
    ]
