# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20180507_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_data',
            name='loan_type',
            field=models.IntegerField(choices=[(0, 'TYPE_FIXED'), (1, 'TYPE_ARM')], default=0),
        ),
    ]
