# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_auto_20180507_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_data',
            name='borrower_type',
            field=models.IntegerField(choices=[(0, 'Sole Proprietorship'), (1, 'General Partnership'), (2, 'Limited Partnership'), (3, 'C-Corporation'), (4, 'S-Corporation'), (5, 'Limited Liability Company')], default=0),
        ),
    ]
