# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_auto_20180509_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_data',
            name='TLC_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='wwwtlc.Wallet'),
        ),
    ]
