# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_auto_20180509_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='wwwtlc.Borrower', verbose_name='Borrower ID'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_address',
            field=models.ForeignKey(help_text='The address of the property needing financed', on_delete=django.db.models.deletion.CASCADE, related_name='loan_address', to='wwwtlc.Address'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_payment_quantity',
            field=models.IntegerField(help_text='Months until loan is paid'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_payment_request',
            field=models.DecimalField(decimal_places=4, help_text='Desired monthly payment', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_payment_required',
            field=models.DecimalField(decimal_places=4, help_text='Approved monthly payment', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='borrower_requested',
            field=models.CharField(help_text='At time of loan request, the person/entity trying to borrow the money', max_length=60),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='contact_person',
            field=models.ForeignKey(help_text='The facilitator for loan processing', on_delete=django.db.models.deletion.CASCADE, related_name='contact_person', to='wwwtlc.Person'),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_address',
            field=models.ForeignKey(help_text='The address of the property needing financed', on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.Address'),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_balance',
            field=models.DecimalField(decimal_places=18, help_text='Remaining balance left on loan', max_digits=80),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_intrate_current',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Current interest rate'),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_intrate_start',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Starting interest rate'),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_type',
            field=models.IntegerField(choices=[(0, 'FIXED'), (1, 'ARM')], default=0),
        ),
    ]
