# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_auto_20180509_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_data',
            name='borrower_requested',
            field=models.CharField(help_text='At time of loan request, the person/entity trying to borrow the money', max_length=60, verbose_name='Borrower'),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='contracts',
            field=models.ForeignKey(blank=True, help_text='(optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.Contract'),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_approve_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_partner', to='wwwtlc.Partner'),
        ),
    ]
