# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-12 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_auto_20180509_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_data',
            name='TLC_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='wwwtlc.Wallet'),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_balance',
            field=models.DecimalField(blank=True, decimal_places=18, help_text='Remaining balance left on loan', max_digits=80, null=True),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_interest_paid',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_intrate_current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Current interest rate'),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_intrate_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Starting interest rate'),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_partner',
            field=models.ForeignKey(blank=True, help_text='(optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_partner', to='wwwtlc.Partner'),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_principle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_principle_paid',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
