# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wwwtlc', '__first__'),
        ('loan', '0013_auto_20180514_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_requested', models.CharField(help_text='At time of loan request, the person/entity trying to borrow the money', max_length=60, verbose_name='Borrower')),
                ('loan_request_amt', models.DecimalField(decimal_places=4, max_digits=12)),
                ('loan_payment_request', models.DecimalField(decimal_places=4, help_text='Desired monthly payment', max_digits=12)),
                ('loan_intrate_request', models.DecimalField(decimal_places=2, max_digits=4)),
                ('loan_request_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.IntegerField(choices=[(0, 'Incomplete'), (1, 'Processing'), (2, 'Completed'), (3, 'N/A')], default=0)),
                ('verification_status', models.IntegerField(choices=[(0, 'Incomplete'), (1, 'Processing'), (2, 'Completed'), (3, 'N/A')], default=0)),
                ('approval_status', models.IntegerField(choices=[(0, 'Incomplete'), (1, 'Processing'), (2, 'Completed'), (3, 'N/A')], default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loan_payment_required',
            new_name='loan_payment_due',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loan_request_date',
            new_name='loan_payment_due_date',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loan_payment_quantity',
            new_name='payments_left',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_address',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_officer',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_payment_request',
        ),
        migrations.RemoveField(
            model_name='loan_data',
            name='TLC_balance',
        ),
        migrations.RemoveField(
            model_name='loan_data',
            name='borrower_requested',
        ),
        migrations.RemoveField(
            model_name='loan_data',
            name='loan_approve_date',
        ),
        migrations.RemoveField(
            model_name='loan_data',
            name='loan_balance',
        ),
        migrations.RemoveField(
            model_name='loan_data',
            name='loan_interest_paid',
        ),
        migrations.RemoveField(
            model_name='loan_data',
            name='loan_intrate_current',
        ),
        migrations.RemoveField(
            model_name='loan_data',
            name='loan_intrate_start',
        ),
        migrations.RemoveField(
            model_name='loan_data',
            name='loan_principle',
        ),
        migrations.RemoveField(
            model_name='loan_data',
            name='loan_principle_paid',
        ),
        migrations.AddField(
            model_name='loan',
            name='TLC_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='wwwtlc.Wallet'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_approve_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_balance',
            field=models.DecimalField(blank=True, decimal_places=18, help_text='Remaining balance left on loan', max_digits=80, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_interest_paid',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_intrate_current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Current interest rate'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_intrate_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Starting interest rate'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_principal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_principal_paid',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_data', to='loan.Loan_Data'),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_partner',
            field=models.ForeignKey(blank=True, default=0, help_text='(optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_partner', to='wwwtlc.Partner'),
        ),
        migrations.AddField(
            model_name='loan_workflow',
            name='loan_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan.Loan_Data'),
        ),
        migrations.AddField(
            model_name='loan_workflow',
            name='loan_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_officer', to='wwwtlc.Person'),
        ),
    ]
