# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_auto_20180511_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_data',
            name='loan_balance',
            field=models.DecimalField(blank=True, decimal_places=18, help_text='Remaining balance left on loan', max_digits=80, null=True),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_partner',
            field=models.ForeignKey(blank=True, help_text='(optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_partner', to='wwwtlc.Partner'),
        ),
    ]
