# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_auto_20180517_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrower_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='wwwtlc.Borrower', verbose_name='Borrower ID'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_approve_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_balance',
            field=models.DecimalField(decimal_places=18, default=0, help_text='Remaining balance left on loan', max_digits=80),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_interest_paid',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_intrate_current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Current interest rate'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_intrate_start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Starting interest rate'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_principal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_principal_paid',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
