# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0015_auto_20180517_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_balance',
            field=models.DecimalField(decimal_places=18, help_text='Remaining balance left on loan', max_digits=80),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_interest_paid',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_intrate_current',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Current interest rate'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_intrate_start',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Starting interest rate'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_principal',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_principal_paid',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
