# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0016_auto_20180517_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_workflow',
            name='verification_status',
        ),
    ]
