# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wwwtlc', '__first__'),
        ('loan', '0017_remove_loan_workflow_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_wallet',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='wwwtlc.Wallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='TLC_balance',
            field=models.DecimalField(decimal_places=18, default=0, help_text='TLC owned by TLC from loan payment', max_digits=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan_request',
            name='loan_intrate_request',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Desired interest rate'),
        ),
        migrations.AlterField(
            model_name='loan_request',
            name='loan_request_amt',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Desired loan amount'),
        ),
        migrations.AlterField(
            model_name='loan_workflow',
            name='approval_status',
            field=models.IntegerField(choices=[(0, 'Denied'), (1, 'Approved')], default=0),
        ),
    ]
