# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-15 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwtlc', '__first__'),
        ('loan', '0019_auto_20180614_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.IntegerField(choices=[(0, 'Incomplete'), (1, 'Processing'), (2, 'Completed'), (3, 'N/A')], default=0)),
                ('approval_status', models.IntegerField(choices=[(0, 'Denied'), (1, 'Approved')], default=0)),
                ('loan_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan.Loan_Data')),
                ('loan_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_officer', to='wwwtlc.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='loan',
            name='TLC_balance',
            field=models.DecimalField(decimal_places=18, help_text='TLC owned by TLC from loan payment', max_digits=65),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_balance',
            field=models.DecimalField(decimal_places=18, help_text='Remaining balance left on loan', max_digits=65),
        ),
    ]
