# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0020_auto_20180615_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_data',
            name='loan_partner',
            field=models.ForeignKey(blank=True, default=1, help_text='(optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_partner', to='wwwtlc.Partner'),
        ),
    ]
