# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-12 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0021_auto_20180619_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_request',
            name='request_data',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='loan.Loan_Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan_request',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
