# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0022_auto_20180712_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_request',
            name='loan_request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
