# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-12 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0023_auto_20180712_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_request',
            name='workflow_status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Sleep'), (2, 'Tier 1'), (3, 'Tier 2'), (4, 'Priority')], default=0),
        ),
    ]
