# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0024_loan_request_workflow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_request',
            name='workflow_status',
            field=models.IntegerField(choices=[(0, 'Sleep'), (1, 'Active'), (2, 'Tier 1'), (3, 'Tier 2'), (4, 'Priority')], default=1),
        ),
    ]
